#!/bin/bash
# Copyright (c) 2013 Jakub Suder, licensed under MIT license
# version: 2013-03-05
# http://github.com/jsuder/git-code-review

usage() {
  echo "usage: git code-review [options]"
  echo
  echo "  -i   interactive mode - review changesets (see config options below)"
  echo "  -n   dry run - prints changes but doesn't update any files"
  echo "  -h   prints this help"
  echo
  echo "config options: "
  echo "   code-review.command   default is \"git log -p\" (applies only when -i is provided)"
  echo "   code-review.auto      if true, will not prompt before entering interactive review (applies only when -i is provided)"
  echo
}

while getopts "inh" OPTION; do
  case $OPTION in
    i)
      INTERACTIVE=1
      ;;
    h)
      usage
      exit 1
      ;;
    n)
      DRY_RUN=1
      ;;
  esac
done

REPO=$(git rev-parse --show-toplevel)
if [ -z "$REPO" ]; then
  exit 1
fi

REVIEW_DIR="$REPO/.git/review"
if [ ! -e "$REVIEW_DIR" ]; then
  mkdir "$REVIEW_DIR"
fi

REVIEW_COMMAND=$(git config code-review.command)
if [ -z "$REVIEW_COMMAND" ]; then
  REVIEW_COMMAND="git log -p"
fi

REVIEW_AUTO=$(git config code-review.auto)
if [ "$REVIEW_AUTO" != "true" ]; then
  REVIEW_AUTO="false"
fi

echo "Fetching latest updates..."
git fetch

# get all currently existing remote branches
REMOTE_BRANCHES=$(git branch -r | grep -v " ->")

for BRANCH in $REMOTE_BRANCHES; do
  NEW_HASH=$(git rev-parse --short $BRANCH)
  HASH_FILE="$REVIEW_DIR/$BRANCH"
  REMOTE=$(echo $BRANCH | cut -d '/' -f 1)
  REMOTE_URL=$(git remote show -n $REMOTE | grep "Fetch URL:")
  GITHUB_URL=$(echo "$REMOTE_URL" | grep -E -o 'github.com[:/].*' | sed -e 's/:/\//' -e 's/\.git$//')
  # find the main branch for compare links
  if [ $(git rev-parse -q --verify $REMOTE/develop) ]; then
    MAIN_BRANCH=develop
  elif [ $(git rev-parse -q --verify $REMOTE/master) ]; then
    MAIN_BRANCH=master
  fi
  SKIP=0

  if [ -e "$HASH_FILE" ]; then
    # branch existed before, print revisions
    OLD_HASH=$(cat "$HASH_FILE")

    if [ $OLD_HASH != $NEW_HASH ]; then
      echo

      if [ "$(git branch -r --contains $OLD_HASH | grep -v " ->" | grep "$BRANCH$")" ]; then
        echo "Branch $BRANCH updated: $OLD_HASH..$NEW_HASH"

        if [ "$GITHUB_URL" ]; then
          echo " -> https://$GITHUB_URL/compare/$OLD_HASH...$NEW_HASH"
        fi

        if [ $INTERACTIVE ]; then
          if [ "$REVIEW_AUTO" == "true" ]; then
            $REVIEW_COMMAND $OLD_HASH..$NEW_HASH
          else
            read -p "Review? Y(es)/n(o)/l(ater): " ynl
            case $ynl in
              [Yy]* )
                $REVIEW_COMMAND $OLD_HASH..$NEW_HASH
                ;;
              [Nn]* )
                ;;
              [Ll]* ) SKIP=1;
                ;;
              * ) 
                $REVIEW_COMMAND $OLD_HASH..$NEW_HASH
                ;;
            esac
          fi
        fi
        if [ $SKIP == 0 ]; then
          FOUND=1
        fi
      else
        echo "The history of $BRANCH is different since last code review (expected to find $OLD_HASH). ($OLD_HASH -> $NEW_HASH)"
        if [ "$MAIN_BRANCH" -a "$GITHUB_URL" ]; then
          echo " -> https://$GITHUB_URL/compare/$MAIN_BRANCH...$NEW_HASH"
        fi
      fi
    fi
  else
    # new branch created - prepare parent directories
    DIR=$(dirname "$HASH_FILE")
    mkdir -p "$DIR"

    if [ "$MAIN_BRANCH" ]; then
      if [ ! "$(git branch -r --contains $NEW_HASH | grep -v " ->" | grep "$REMOTE/$MAIN_BRANCH$")" ]; then
        echo
        echo "Branch $BRANCH created: $REMOTE/$MAIN_BRANCH..$NEW_HASH"

        if [ "$GITHUB_URL" ]; then
          echo " -> https://$GITHUB_URL/compare/$MAIN_BRANCH...$NEW_HASH"
        fi

        if [ $INTERACTIVE ]; then
          if [ "$REVIEW_AUTO" == "true" ]; then
            $REVIEW_COMMAND $MAIN_HASH..$NEW_HASH
          else
            read -p "Review? Y(es)/n(o)/l(ater): " ynl
            case $ynl in
              [Yy]* )
                $REVIEW_COMMAND $MAIN_HASH..$NEW_HASH
                ;;
              [Nn]* )
                ;;
              [Ll]* ) SKIP=1;
                ;;
              * ) 
                $REVIEW_COMMAND $OLD_HASH..$NEW_HASH
                ;;
            esac
          fi
        fi

        if [ $SKIP == 0 ]; then
          FOUND=1
        fi
      fi
    else
      echo
      echo "Branch $BRANCH created: $NEW_HASH"

    fi
  fi

  if [ -z "$DRY_RUN" ]; then
    if [ $SKIP == 0 ]; then
      # update saved revision
      echo $NEW_HASH > "$HASH_FILE"
    fi
  fi

done

# check old branches
EXISTING_BRANCHES=$(find "$REVIEW_DIR/" -type f -and -not -name '.*' | sed -E -e 's/.*\.git\/review\/+//')

for BRANCH in $EXISTING_BRANCHES; do
  if [[ "$REMOTE_BRANCHES" != *$BRANCH* ]]; then
    HASH_FILE="$REVIEW_DIR/$BRANCH"
    OLD_HASH=$(cat "$HASH_FILE")

    echo "Branch $BRANCH removed (was: $OLD_HASH)"

    if [ -z "$DRY_RUN" ]; then
      rm "$HASH_FILE"
    fi
  fi
done

echo
if [ $FOUND ]; then
  echo "You did it! Great job!"
else
  echo "Nothing to review, back to work!"
fi
